# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/dev/FPGA/PQM_gen/georadar_gen/IP/dds8_mod_fi_partial/dds8_mod_fi_partial.xci
# IP: The module: 'dds8_mod_fi_partial' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/dev/FPGA/PQM_gen/georadar_gen/IP/dds8_mod_fi_partial/dds8_mod_fi_partial_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds8_mod_fi_partial'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/dev/FPGA/PQM_gen/georadar_gen/IP/dds8_mod_fi_partial/dds8_mod_fi_partial.xci
# IP: The module: 'dds8_mod_fi_partial' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/dev/FPGA/PQM_gen/georadar_gen/IP/dds8_mod_fi_partial/dds8_mod_fi_partial_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds8_mod_fi_partial'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
