# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/dds8_mod_group_accum/dds8_mod_group_accum.xci
# IP: The module: 'dds8_mod_group_accum' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/dds8_mod_group_accum/dds8_mod_group_accum_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds8_mod_group_accum'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/dds8_mod_group_accum/dds8_mod_group_accum.xci
# IP: The module: 'dds8_mod_group_accum' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/dds8_mod_group_accum/dds8_mod_group_accum_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds8_mod_group_accum'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
