# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/dev/FPGA/PQM_gen/mult_14_14/mult_14_14.xci
# IP: The module: 'mult_14_14' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/dev/FPGA/PQM_gen/mult_14_14/mult_14_14_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_14_14'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/dev/FPGA/PQM_gen/mult_14_14/mult_14_14.xci
# IP: The module: 'mult_14_14' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/dev/FPGA/PQM_gen/mult_14_14/mult_14_14_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_14_14'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
