# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dds_lut_25x16/dds_lut_25x16.xci
# IP: The module: 'dds_lut_25x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/dds_lut_25x16/dds_lut_25x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_lut_25x16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: ip/dds_lut_25x16/dds_lut_25x16.xci
# IP: The module: 'dds_lut_25x16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/dds_lut_25x16/dds_lut_25x16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_lut_25x16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
