# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dds8_mod_fi_add/dds8_mod_fi_add.xci
# IP: The module: 'dds8_mod_fi_add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/dds8_mod_fi_add/dds8_mod_fi_add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds8_mod_fi_add'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: ip/dds8_mod_fi_add/dds8_mod_fi_add.xci
# IP: The module: 'dds8_mod_fi_add' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/dds8_mod_fi_add/dds8_mod_fi_add_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds8_mod_fi_add'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
