# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/dev/FPGA/PQM_gen/pg_freq_acc_32to40plus/pg_freq_acc_32to40plus.xci
# IP: The module: 'pg_freq_acc_32to40plus' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/dev/FPGA/PQM_gen/pg_freq_acc_32to40plus/pg_freq_acc_32to40plus_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pg_freq_acc_32to40plus'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/dev/FPGA/PQM_gen/pg_freq_acc_32to40plus/pg_freq_acc_32to40plus.xci
# IP: The module: 'pg_freq_acc_32to40plus' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/dev/FPGA/PQM_gen/pg_freq_acc_32to40plus/pg_freq_acc_32to40plus_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pg_freq_acc_32to40plus'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
