# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/dev/FPGA/PQM_gen/georadar_gen.cache/wt [current_project]
set_property parent.project_path C:/dev/FPGA/PQM_gen/georadar_gen.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/dev/FPGA/PQM_gen/georadar_gen.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/dev/FPGA/PQM_gen/SIM/BRAM_Init.coe
read_vhdl -library xil_defaultlib {
  C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/imports/PQM_gen/SRC/main_pkg.vhd
  C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/imports/PQM_gen/SRC/amp_ctrl.vhd
  C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/imports/PQM_gen/SRC/dds8_pacc.vhd
  C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/imports/PQM_gen/SRC/sequencer.vhd
  C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/imports/PQM_gen/SRC/mod.vhd
  C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/imports/PQM_gen/SRC/envelope_shaper.vhd
  C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/imports/PQM_gen/SRC/core.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/imports/PQM_gen/SRC/dds8_mod.vhd
read_ip -quiet C:/dev/FPGA/PQM_gen/georadar_gen.srcs/pg_freq_acc_32to40plus/ip/pg_freq_acc_32to40plus/pg_freq_acc_32to40plus.xci
set_property used_in_implementation false [get_files -all c:/dev/FPGA/PQM_gen/georadar_gen.srcs/pg_freq_acc_32to40plus/ip/pg_freq_acc_32to40plus/pg_freq_acc_32to40plus_ooc.xdc]

read_ip -quiet C:/dev/FPGA/PQM_gen/georadar_gen.srcs/dds8_mod_fi_add/ip/dds8_mod_fi_add/dds8_mod_fi_add.xci
set_property used_in_implementation false [get_files -all c:/dev/FPGA/PQM_gen/georadar_gen.srcs/dds8_mod_fi_add/ip/dds8_mod_fi_add/dds8_mod_fi_add_ooc.xdc]

read_ip -quiet C:/dev/FPGA/PQM_gen/georadar_gen.srcs/dds8_mod_fi_partial/ip/dds8_mod_fi_partial/dds8_mod_fi_partial.xci
set_property used_in_implementation false [get_files -all c:/dev/FPGA/PQM_gen/georadar_gen.srcs/dds8_mod_fi_partial/ip/dds8_mod_fi_partial/dds8_mod_fi_partial_ooc.xdc]

read_ip -quiet C:/dev/FPGA/PQM_gen/georadar_gen.srcs/mult_14_14/ip/mult_14_14/mult_14_14.xci
set_property used_in_implementation false [get_files -all c:/dev/FPGA/PQM_gen/georadar_gen.srcs/mult_14_14/ip/mult_14_14/mult_14_14_ooc.xdc]

read_ip -quiet C:/dev/FPGA/PQM_gen/georadar_gen.srcs/dds_lut_25x16/ip/dds_lut_25x16/dds_lut_25x16.xci
set_property used_in_implementation false [get_files -all c:/dev/FPGA/PQM_gen/georadar_gen.srcs/dds_lut_25x16/ip/dds_lut_25x16/dds_lut_25x16_ooc.xdc]

read_ip -quiet C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/dds8_mod_group_accum/dds8_mod_group_accum.xci
set_property used_in_implementation false [get_files -all c:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/dds8_mod_group_accum/dds8_mod_group_accum_ooc.xdc]

read_ip -quiet C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/mult_16_14/mult_16_14.xci
set_property used_in_implementation false [get_files -all c:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/mult_16_14/mult_16_14_ooc.xdc]

read_ip -quiet C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top CORE -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CORE.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file CORE_utilization_synth.rpt -pb CORE_utilization_synth.pb"
