# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/mult_16_14/mult_16_14.xci
# IP: The module: 'mult_16_14' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/mult_16_14/mult_16_14_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_16_14'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/mult_16_14/mult_16_14.xci
# IP: The module: 'mult_16_14' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/dev/FPGA/PQM_gen/georadar_gen.srcs/sources_1/ip/mult_16_14/mult_16_14_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_16_14'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
